#ifndef TILES_H
#define TILES_H

// which VRAM tile slots hold which art
// slot 0 stays blank b/c empty tilemap cells point at it
#define TILE_MARKER 1
#define TILE_BAR_FIRST 2
#define TILE_BAR_DARK_FIRST (TILE_BAR_FIRST + 9)
#define TILE_DIGIT_FIRST (TILE_BAR_DARK_FIRST + 3)
#define TILE_FONT_FIRST (TILE_DIGIT_FIRST + 10)
#define TILE_EXCLAIM (TILE_FONT_FIRST + 26)
#define TILE_LETTER_M (TILE_FONT_FIRST + 12)
#define TILE_BOULDER_FIRST (TILE_EXCLAIM + 1)
#define TILE_SISYPHUS_FIRST (TILE_BOULDER_FIRST + 16)
#define TILE_SCENE_FIRST (TILE_SISYPHUS_FIRST + 16)
#define TILE_FULLSCREEN_FIRST (TILE_SCENE_FIRST + 34)

#define BAR_BORDER_PX 4
#define BAR_TILE_COL 1
#define BAR_TILE_ROW 16
#define BAR_WIDTH_TILES 9

#define FLASH_TILE_OFFSET 3
#define FLASH_TILE_COUNT 3

#define ALTITUDE_TILE_COL 15
#define ALTITUDE_TILE_ROW 1

#define BOULDER_OAM_Y (DEVICE_SCREEN_PX_HEIGHT - 53)
#define BOULDER_OAM_X (55 + 8)
#define SISYPHUS_OAM_Y (DEVICE_SCREEN_PX_HEIGHT - 46)
#define SISYPHUS_OAM_X (40 + 8)
#define OAM_IDX_BOULDER 1
#define OAM_IDX_SISYPHUS 5

#define ACTOR_FRAME_PUSH 4
#define ACTOR_FRAME_MISS 8
#define BOULDER_FRAME_ROLL 12
#define SISYPHUS_FRAME_DESPAIR 12

#define POSE_IDLE 0
#define POSE_PUSH 1
#define POSE_MISS 2
#define POSE_DESPAIR 3

#endif
