#ifndef TUNING_H
#define TUNING_H

#define CYCLE_FRAMES 60
#define MARKER_CYCLE_MIN 4
#define MARKER_PAUSE_FRAMES 4
#define BAR_INNER_WIDTH 64
#define METRES_PER_SPEEDUP 10
#define HIT_REWARD 10
#define HIT_FREEZE_FRAMES 12
#define MISS_LIMIT 3
#define MISS_PENALTY_DIV 10
#define MISS_FREEZE_FRAMES 4
#define MISS_POSE_FRAMES 24
#define SLIP_FRAMES 30
#define SWEET_SPOT_WIDTH 12
#define SWEET_SPOT_MIN ((BAR_INNER_WIDTH - SWEET_SPOT_WIDTH) / 2)
#define SWEET_SPOT_MAX (SWEET_SPOT_MIN + SWEET_SPOT_WIDTH - 1)

#endif
